apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nodejs-health-check-se2y
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nodejs-health-check-se2y
    app.kubernetes.io/part-of: e2e-nodejs
  name: nodejs-health-check-se2y
  namespace: e2e-demos-pogv-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: nodejs-health-check-se2y
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: nodejs-health-check-se2y
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/test-images-protected@sha256:d8e2614697bc3ca91ec4a1fa561a60772cc277dda08e14e293c85168f6c187e1
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
